#+TITLE: Rapport du projet 7 colors
#+AUTHOR: Marco Freire et Clément Legrand
#+DATE: 2017
#+LANG: francais
#+STARTUP: overview indent inlineimages
#+OPTIONS: toc:nil num:t ^:nil h:5 num:4
#+TAGS: noexport(n)
#+EXPORT_EXCLUDE_TAGS: noexport
#+LATEX_CLASS: myarticle
#+LATEX_CLASS_OPTIONS: [12pt,a4paper,twoside]
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage{amsmath,amssymb,gensymb,mathtools}
#+LATEX_HEADER: \usepackage{xspace}
#+LATEX_HEADER: \usepackage[paper=a4paper,textwidth=6.6in,top=38mm,bottom=38mm]{geometry} % ,left=20mm,right=20mm, ,headsep=0pt
#+LATEX_HEADER: %\usepackage{a4wide}
#+LATEX_HEADER: \usepackage{palatino}
#+LATEX_HEADER: \usepackage{verbments}
#+LATEX_HEADER: \plset{numbers=left,numbersep=5pt,texcl=true,style=tango,bgcolor=Moccasin,fontsize=\small}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{todonotes}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage[normalem]{ulem}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \AtBeginDocument{
#+LATEX_HEADER:   \definecolor{pdfurlcolor}{rgb}{0,0,0.6}
#+LATEX_HEADER:   \definecolor{pdfcitecolor}{rgb}{0,0.6,0}
#+LATEX_HEADER:   \definecolor{pdflinkcolor}{rgb}{0.6,0,0}
#+LATEX_HEADER:   \definecolor{light}{gray}{.85}
#+LATEX_HEADER:   \definecolor{vlight}{gray}{.95}
#+LATEX_HEADER:   \selectlanguage{francais}
#+LATEX_HEADER: }
#+LATEX_HEADER: \usepackage{url} \urlstyle{sf}
#+LATEX_HEADER: \usepackage[francais]{babel}
#+LATEX_HEADER: \selectlanguage{francais}
#+LATEX_HEADER: \let\oldmaketitle=\maketitle
#+LATEX_HEADER: \def\maketitle{}
#+LATEX_HEADER: \usepackage[colorlinks=true,citecolor=pdfcitecolor,urlcolor=pdfurlcolor,linkcolor=pdflinkcolor,pdfborder={0 0 0}]{hyperref}
#+LATEX_HEADER: \pagestyle{fancy}\fancyhead{}\fancyfoot{}
#+LATEX_HEADER: \usepackage{subfigure}
#+LATEX_HEADER: %\usepackage[nomarkers,figuresonly]{endfloat}\renewcommand{\efloatseparator}{\mbox{}}

#+BEGIN_LaTeX
\renewcommand{\v}[1]{\ensuremath{\overrightarrow{#1}}\xspace}
\let\oldcite=\cite
\def\cite#1{~\oldcite{#1}\xspace}
\let\oldref=\ref
\def\ref#1{~\oldref{#1}\xspace}
\let\oldeqref=\eqref
\def\eqref#1{~\oldeqref{#1}\xspace}
\let\leq=\leqslant
\let\geq=\geqslant
\let\le=\leqslant
\let\ge=\geqslant
\def\R{\ensuremath{\mathbb{R}}\xspace}
\pagestyle{empty} 
\pagenumbering{gobble}
\let\maketitle=\oldmaketitle

\pagestyle{fancy}
\fancyhead{}
\fancyfoot{}
\rhead[\sffamily\itshape \MakeUppercase{Rapport}]{\thepage}
\lhead[\thepage]{\sffamily\itshape \leftmark}
\pagenumbering{roman}
\pagenumbering{arabic}

#+END_LaTeX

#+BEGIN_CENTER
   \bgroup\bf \LARGE Rapport du projet 7 colors\egroup\medskip

   \large Marco Freire et Clément Legrand \smallskip

   \normalsize L3 Info ENS, 2017/2018
#+END_CENTER

* TODO À faire [0/12]                                              :noexport:
  - [ ] compléter l'introduction 
  - [ ] finir de répondre question 1
  - [ ] trouver comment afficher avec \ texttt des noms comportant un
    _
  - [ ] comprendre comment supprimer l'intégralité d'un objet de type
    boardd, pas juste les cases
  - [ ] calcul de la complexité amortie pour la question 2.
  - [ ] Question 4
  - [ ] Question 6
  - [ ] Question 7
  - [ ] faire s'affronter les IA + Question 10
  - [ ] Réfléchir à la question 13
  - [ ] implémenter le glouton prévoyant sur $m$ coups.
  - [ ] régler la bibliographie
* Raccourcis claviers   :noexport:
** Emacs
   | Raccourci | Commande                     |
   |-----------+------------------------------|
   | C-x C-c   | exit                         |
   | C-x C-s   | save buffer                  |
   | C-g       | mega C-z pour les raccourcis |
   | C-_       | Undo                         |
   | C-s       | search                       |
   | C-x C-h   | get list of Emacs shortcuts  |
   | C-espace  | poser une marque (sélection) |
   | C-w       | couper                       |
   | M-w       | copier                       |
   | C-y       | coller                       |
** Orgmode
   | Raccourci   | Commande                                                              |
   |-------------+-----------------------------------------------------------------------|
   | Tab         | Fold/Unfold                                                           |
   | C-c C-c     | do something usefull                                                  |
   | C-c C-t     | switch todo                                                           |
   | C-c C-e l o | Export as Latex and then process to PDF, open the resulting PDF file. |
   | C-c C-e l p | Exprot as Latex and then process to PDF.                              |
** Police et insertion
   | Raccourci | Commande |
   |-----------+----------|
   | / /       | italique |
   | * *       | gras     |
   | _ _       | souligné |
   | + +       | rayé     |
http://www.tuteurs.ens.fr/unix/editeurs/emacs_memo.html#s5

* Introduction
  Seven colors est un jeu d'ordinateur inventé par Dmitry Pashkov,
  développé en 1991. Le principe est simple: deux joueurs essayent de
  conquérir la plus grande surface d'un terrain de jeu constitué de
  cases juxtaposées, de sept couleurs différentes. Pour cela, chaque
  joueur choisit à son tour une couleur, et conquiert toute case de
  cette couleur adjacente à la zone qu'il possède.

* Réponses aux questions
** Voir le monde en sept couleurs
*** Question 1
   Il convient tout d'abord de créer un type \texttt{boardd} afin
   d'encapsuler un peu le code et de ne pas modifier le plateau de jeu
   n'importe comment. Ce type contient un tableau de char de taille
   $ \texttt{BOARDSIZE} ^{2}$, ainsi que deux entiers:
   \texttt{numcellsup} et \texttt{numcellsdown} indiquant le nombre de
   cases possédées par le joueur ^ et le joueur v respectivement.
   Afin de maintenir cette structure, nous avons implémenté les
   méthodes \texttt{getcell}, \texttt{getnumcellsup},
   \texttt{getnumcellsup}, \texttt{setcell}, ainsi que
   \texttt{boardcreate}} et \texttt{boardfree}, allouant un tableau de
   la bonne taille, et le libérant respectivement. 

*** Question 2   
**** Complexité dans le pire cas :
Dans le pire des cas, à chaque itération, l'algorithme met à jour une
et une seule case. Posons $n = BOARDSIZE$. Étant donné qu'il y a $n^{2}$
cases dans le tableau, au plus $n^{2}$ passages sont effectués. Lors d'un
passage, $n^{2}$ cases sont examinées, chacune d'elles en un temps
contant. La complexité dans le pire cas de cet algorithme est donc un
$O(n^4)$.
Cette borne est réellement atteinte: par exemple si une couleur forme
une spirale rectangulaire jusqu'au centre. La complexité est donc un
$\Theta(n^{2})$. 
**** Complexité amortie :
Le cas énoncé précédemment est assez pathologique et ne peut se
produire trop souvent. L'analyse de la complexité amortie est donc
pertinente.
*** Question 3 (bonus)
**** Principe de l'algorithme implémenté :
Plutôt que d'effectuer des parcours entier du tableau en vérifiant si
les cases ont besoin d'être mises à jour, il est préférable de se
représenter la zone conquise pas un joueur comme un graphe (non
orienté), dont les sommets sont les toutes les cases du tableau et les
arêtes lient chacune des cases conquises par le joueur aux quatre
cases adjacentes sur le plateau. Il suffit alors d'effectuer un
parcours de ce graphe en le mettant a jour progressivement. 

Nous créons pour cela un second tableau \texttt{boardvisited}, de
mêmes dimensions, dont les cases indiquent si le sommet $(i,j)$ a été
visité ou pas. Nous parcourons ensuite récursivement le graphe est
commençant par la case du coin, qui appartient forcement au joueur. À
chaque sommet visité, nous le marquons comme tel dans
\texttt{boardvisited}, et s'il est de la bonne couleur ou appartient au
joueur courant, nous marquons la case celle du joueur dans
\texttt{board} et explorons ses voisines non visitées.
**** Complexité dans le pire des cas :
Chaque case du tableau est visité un nombre fini borné de fois (au
plus quatre dans notre implémentation), donc l'algorithme est un
$O(n^{2})$. 
Là encore, cette borne peut être atteinte si tout le tableau
est de la même couleur. La complexité est donc un $\Theta(n^{2})$.
** À la conquête du monde
*** Question 4
*** Question 5
La partie peut s'arrêter si l'un des joueurs au moins détient plus de
la moitié du plateau de jeu. Nous avons donc recours aux attributs
\texttt{numcellsup} et \texttt{numcellsdown} du type \texttt{boardd},
afin de savoir si ceux ci excèdent la moitié du nombre de cases total.

** La stratégie de l'aléa
*** Question 6
*** Question 7
** La loi du plus fort
*** Question 8
Nous allons pour cela reprendre et modifier légèrement la fonction
\texttt{updateboardoptimized} impémentée pour la question 3, mais en
comptant le nombre de cases modifiables en jouant une couleur donnée au
lieu de les modifier. Nous effectuons ensuite le choix maximisant ce
nombre de cases.
*** Question 9
Pour que le combat soit "équitable", le mieux est de faire s'affronter
les deux joueurs artificiels sur un plateau donné, puis d'effectuer
l'affrontement à nouveau, mais en échangeant les positions de départ.
*** Question 10
** Les nombreuses huitièmes merveilles du monde (bonus)
*** Question 11
Il apparaît facilement qu'en effectuant un parcours entier du plateau
et en comptant les cases ayant parmi leurs voisines, un appartenant au
joueur courant, il est possible d'obtenir le périmètre de la zone
détenue par le joueur en $\Theta(n^{2})$. Il suffit dés lors, pour chaque
couleur possible, de créer une copie du plateau, d'effectuer sur celle
ci une mise à jour en jouant ladite couleur, et de compter le
périmètre correspondant.
La complexité de cet algorithme est donc un $\Theta(n^{2})$.
*** Question 12 
Une des manières d'implémenter le glouton prévoyant est d'effectuer
pour chacune des couleurs une copie du plateau de jeu, puis de
modifier celui ci en jouant cette couleur, en comptant le nombre de
cases ainsi gagnés. Puis d'utiliser la fonction de la question 8 pour
chacune des couleurs afin d'obtenir le nombre maximal de cases gagnées
en ayant fixé le premier coup. On choisit ensuite le premier coup afin
de maximiser ce nombre.  Cet algorithme effectue 7 copies du plateau
en $\Theta(n^{2})$, fait sept appels à \texttt{updateboardoptimized} en
$\Theta(n^{2})$ et fait appel 49 fois à la fonction
\texttt{calcnewcellsoptimized} qui s'exécute en $\Theta(n^{2})$. Il s'exécute
donc en $\Theta(n^{2})$.
Si on veut explorer $m$ coups consécutifs, cette complexité passe à un
$\Theta(\exp(m)*n^{2})$, car il faut alors effectuer 7 fois plus de copies du
tableau pour chaque coup additionnel (sauf le dernier ou il est possible
d'utiliser \texttt{calcnewcellsoptimized}).
** Le pire du monde merveilleux des sept couleurs (bonus)
*** Question 13
* Conclusion
#+LaTeX: \label{sec:conclusion}

#+LaTeX: \clearpage\appendix

* Annexe
** Bibliographie
Ne sont cités ici que les ouvrages et sites dont je me suis le plus
servi.

# [1] http://pauillac.inria.fr/~quercia/documents-info/Luminy-2003/schabanel/schabanel.pdf

#+LaTeX: \def\section*#1{}
#+LaTeX: \bibliographystyle{abbrv-fr}
#+LaTeX: \nocite{*}
#+LaTeX: \bibliography{biblio.bib}
#+LaTeX: \clearpage
** Résumé                                                         :noexport:
* Emacs setups                                                     :noexport:
# Local Variables:
# eval:   (setq org-export-babel-evaluate nil)
# eval:   (unless (boundp 'org-latex-classes) (setq org-latex-classes nil))
# eval:   (add-to-list 'org-latex-classes '("myarticle" "\\documentclass{article}\n \[NO-DEFAULT-PACKAGES]\n \[EXTRA]\n"  ("\\section{%s}" . "\\section*{%s}") ("\\subsection{%s}" . "\\subsection*{%s}") ("\\subsubsection*{%s}" . "\\subsubsection*{%s}") ("\\paragraph*{%s}" . "\\paragraph*{%s}") ("\\subparagraph*{%s}" . "\\subparagraph*{%s}")))
# eval:   (setq ispell-local-dictionary "francais")
# eval:   (setq org-babel-python-command "python3")
# eval:   (eval (flyspell-mode t))
# eval:   (add-to-list 'org-latex-packages-alist '("" "minted"))
# eval:   (setq org-latex-listings 'minted) 
# eval:   (setq org-latex-pdf-process '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f" "bibtex `basename %f .tex`" "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f" "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
# End:
